export const enum UserActionType {
  SET_USER = 'SET_USER',
  SET_CURRENT_COMPANY = 'SET_CURRENT_COMPANY',
  ADD_COMPANY = 'ADD_COMPANY',
  DESTROY_SESSION = 'DESTROY_SESSION',
  SET_USER_COMPANY_DATA = 'SET_USER_COMPANY_DATA',
}
