export const enum AuthActionType {
  UPDATE_TOKEN = 'UPDATE_TOKEN',
  SET_TOKEN_LOADED = 'SET_TOKEN_LOADED',
  LOGOUT = 'LOGOUT',
  MASK_TOKEN = 'MASK_TOKEN',
  REMOVE_MASKED_TOKEN = 'REMOVE_MASKED_TOKEN',
}
